version: '3.9'
services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asis/Seoul
    restart: always

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    volumes:
      - /home/springboot
    depends_on:
      - mariadb
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/hr
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    restart: always
